services:
  pinginator:
    image: ghcr.io/natefox/thepinginator:latest
    ports:
      - "8080:8080"
    environment:
      - PING_HOSTS=8.8.8.8,1.1.1.1
    volumes:
      - pinginator-data:/data
    restart: unless-stopped
    stop_grace_period: 3s

volumes:
  pinginator-data:
